steps:
# Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/dailycrispme', '.']

# Push the Docker image to Google Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/dailycrispme']

# Deploy to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'dailycrispme'
    - '--image'
    - 'gcr.io/$PROJECT_ID/dailycrispme'
    - '--region'
    - 'us-central1' # Change to your desired region
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'

options:
  defaultLogsBucketBehavior: 'REGIONAL_USER_OWNED_BUCKET'
